Solicito Pull Request de la rama CardDev a la Main
ZTStudios/ClimaITNL pull request #1
Opened 2022-06-17 19:54 UTC by JonathanAL003

-En esta rama se hizo el work de la Card

2022-06-17 20:19 UTC, BryanTG1221 requested changes
- Tamaño de Card esta en %, favor de cambiar a px (Figma)
- Icono hacerlo mas grande (Figma)
- Revisar Dots de Update
- Hacer el codigo mas **legible**

2022-06-18 01:02 UTC, JonathanAL003 commented
Ya se hicieron las correciones

2022-06-18 01:36 UTC, BryanTG1221 requested changes
Puntos a corregir

- Script de Deteccion de Fecha, favor de hacerlo en un archivo.js aparte del HTML
- Locacion en el card, unicamente establecer **Nuevo Laredo**
- Implementar los Iconos otorgados en Discord

2022-06-18 02:55 UTC, JonathanAL003 commented
Se hicieron las correciones correspondientes

-Nuevo error: Ya no se muestra la fecha

2022-06-18 21:51 UTC, BryanTG1221 approved these changes
Aprobado, favor de resolver los problemas al hacer el merge

2022-06-18 22:26 UTC, merged